- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disabling the current version of nodejs and enabling nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: addinng user roboshop
    ansible.builtin.user:
      name: roboshop  
  - name: recursively removing app directory
    ansible.builtin.file:
      path: /app
      state: absent
  - name: adding app directory
    ansible.builtin.file:
    path: /app
    state: directory
  - name: downloading the application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  - name: unarchiving catalogue file
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: installing dependencies
    ansible.builtin.command: npm install
      args:
        chdir: /app
  - name: copy catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: daemon reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: copying mongodb repo file
    ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
  - name: installing mongodb client
    ansible.builtin.package:
      name:  mongodb-org-shell
      state: present
  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.myfirstroboshop.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count
  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.myfirstroboshop.online </app/schema/catalogue.js
      when: product_count.stdout == "0"
  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes