- name: Mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copying mongodb repo file
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/momgodb.repo
  - name: installing mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present
  - name: starting and enabling mongodb service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: allowing remote connection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0.'
  - name: restarting mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted


