- name: installing mysql
  hosts: mysql
  become: yes
  tasks:
  - name: disabling the current mysql app
    ansible.builtin.command: dnf module disable mysql -y
  - name: copying mysql repository
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo 
  - name: installing mysql
    ansible.builtin.package:
      name: mysql-community-server
      state: present
  - name: start and enable mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: set root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1   

